### PR TITLE
Add XML options to curl builder

### PR DESCRIPTION
**Pull request by gisheri**
I love the library, and use it quite heavily. 
I deal with some xml apis, so I've added a few small additions to make this library easier to use with XML apis. 

If you feel like it would be helpful to others, feel free to merge it. 

Example Use Case:
```
 $curl = \Utils\Curl::to($url)
            ->withHeaders(static::get_request_headers())
            ->withTimeout(10)
            ->returnResponseArray();
        
        switch($type){
            case "json": 
                $curl->asJson(true)->withData($data);
                break;
            case "xml": 
                $data = $this->xml_encode_request_data($data);
                $curl->asXML()->withXml($data);
                break;
            default: 
                $curl->asUrlEncoded()->withData($data);
                break;
        }
```

### CODE REVIEW

**Comment by elimentz** [comment]
Hey Eric, thanks for this. I definitely see the added value of adding this in, but I need to think about how I want to go about it. Adding this in just as you provide it will work, but it will make it easier to make mistakes, e.g. adding json data to an XML request etc. A major component of this package is that it is easy to use and that includes eliminating the possibility of easy mistakes. So I'd probably have to add some exceptions etc to cover those situations. But we'll make it work!

Out of curiosity: the `application/x-www-form-urlencoded` content type: is it required for XML to work? Or is just something else you use?

Additionally, can you give me some more examples and/or endpoints I can use to test? Would be helpful!

**Comment by gisheri** [comment]
Thanks for the feedback. I could see how you might want to enforce some of those options a bit differently. I'll look into getting some more examples. 

I made the `asUrlEncoded()` function as a shorthand for adding the `application/x-www-form-urlencoded` content type, and to help the calling code to make more of an explicit decision on what kind of request it was sending, now that there are more than just json or not json. (json, urlencoded, or xml)

By default you are sending the POSTFIELDS as an `http_build_query` (url encoded) and most APIs that expect a url encoded body are also most likely expecting to see `application/x-www-form-urlencoded` as the content type. Some of the stricter APIs I've had to integrate with actually threw an error without that header. So the `asUrlEncoded()` function helps make it a little more clear. 

The `asXmlRequest()` adding the `text/xml` content type has been helpful as well, since every XML api I've dealt with expects that header.

**Comment by elimentz** [comment]
In that case I wouldn't add the urlEncoded variable to the options array but just add the header with the `withHeader()` method instead. But that's just a minor fix, don't worry about it.

So all I'd need from you is one or two more examples and ideally an endpoint I can use to test, or some code that will help me set one up and we're good to go

**Comment by elimentz** [comment]
@gisheri Any word on the links or examples?

**Pull request closed without merging**
