### PR TITLE
Enable File Sending. 

### PR DESCRIPTION
**Pull request by Thedigit**
Hi,
Responding to the issue: https://github.com/ixudra/curl/issues/13

I needed this functionality this morning and saw that this feature was not available yet and i figure some one else may need it.  I tried following the original plugin format to make the feature seem less. Updated README.md to reflect the new feature.

I tested this internally and it seems to be working fine.

Thanks

### CODE REVIEW

**Comment by Thedigit** [comment]
Another Note: to format a file route to a curl file format i found/ modified a function
`function getCurlFileValue($filename, $contentType, $postname) {
    // PHP 5.5 introduced a CurlFile object that deprecates the old @filename syntax
    // See: https://wiki.php.net/rfc/curl-file-upload
    if (function_exists('curl_file_create')) {
        return curl_file_create($filename, $contentType, $postname);
    }
    // Use the old style if using an older version of PHP
    $value = "@{$filename};filename=" . $postname;
    if ($contentType) {
        $value .= ';type=' . $contentType;
    }
    return $value;
}`

**Comment by elimentz** [comment]
Thanks for contributing!!

**Comment by elimentz** [comment]
I did some refactoring. It should work, but I'd appreciate it if you could do some testing - in a bit of a rush right now.

**Comment by Thedigit** [comment]
sure thing, one thing kind of missing is the curl file obj i mention above =)

**Comment by elimentz** [comment]
You're right. I'm going to put this into a new issue for now as I have some deadlines that have priority, sorry. Thanks for pointing it out though, this will definitely make the package better!

**Pull request merged**
